package analysis

import (
	"path/filepath"
	"testing"

	"github.com/atul121001/mcpload/cmd/mcpload/internal/report"
)

// The synthetic examples in report/examples are generated by a JS port of this
// package; their verdicts must match what the CLI computes for the same series.
func TestExampleReportsMatchCLIVerdicts(t *testing.T) {
	for _, name := range []string{"healthy", "leaky"} {
		path := filepath.Join("..", "..", "..", "..", "report", "examples", name+".json")
		r, err := report.ReadJSON(path)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		got := Verdicts(r, DefaultConfig())
		got = append(got,
			SessionNotFoundVerdict(float64(r.Summary.ByErrorType["session_not_found"]), float64(r.Summary.Reqs)),
			ThresholdVerdict(r.Thresholds))
		if len(got) != len(r.Verdicts) {
			t.Fatalf("%s: %d verdicts, example has %d", name, len(got), len(r.Verdicts))
		}
		for i, g := range got {
			w := r.Verdicts[i]
			if g.ID != w.ID || g.Status != w.Status || g.Message != w.Message {
				t.Errorf("%s verdict %d:\n cli     %s %s %q\n example %s %s %q", name, i, g.ID, g.Status, g.Message, w.ID, w.Status, w.Message)
			}
		}
	}
}
